### ISSUE TITLE
Text in webpage for derive_param_bsa is a link; not desired?

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiral#967] opened 2022-02-20 19:54 UTC
![Screenshot 2022-02-20 144543](https://user-images.githubusercontent.com/85294667/154861593-c958cf81-5052-41d1-9b92-48389893dec8.jpg)

**Comment by thomas-neitmann** [comment] 2022-02-21 08:22
When building the website this seems to be interpreted as a call to the `sqrt()` function which it inserts a link to.

Anyways, instead of the formula being rendered as code we should make use of LaTeX ot have it properly formatted. See `compute_map()` for an example.

**Comment by esimms999-gsk** [comment] 2022-03-04 14:49
There are a few examples of using LaTex (I think it is LaTex), e.g. compute_map, compute_qtc. And it looks terrible. The equations are shifted off to the right and lose connection with the text description. And what is with that sqrt symbol??


![Screenshot 2022-03-04 094309](https://user-images.githubusercontent.com/85294667/156784229-541b628b-5aba-4815-99e4-173a176330ff.jpg)  


![Screenshot 2022-03-04 094400](https://user-images.githubusercontent.com/85294667/156784243-3d819cf8-dee1-4acd-afc5-e7ec06ce7738.jpg)

**Comment by esimms999-gsk** [comment] 2022-03-04 16:04
I asked for help from RStudio Community:
https://community.rstudio.com/t/pkgdown-want-to-disable-autolink-in-a-line-of-roxygen/130786/2

**Comment by esimms999** [comment] 2022-03-05 21:18
@thomas-neitmann From RStudio Community link, above, someone from RStudio told me they could not reproduce the problem with pkgdown 2.0.2 (we make use of pkgdown 1.5.0). It was quite a bit of work but I managed to make use of pkgdown 2.0.2 and the link for the line with sqrt (Mosteller) is gone:

![Screenshot 2022-03-05 160452](https://user-images.githubusercontent.com/10915780/156900168-36066ca5-3224-468f-9ff5-e7d2d35530b2.jpg)

I don't understand why this seems to work and cannot find much on the autolink functionality of pkgdown.

**Comment by esimms999-gsk** [comment] 2022-03-06 14:21
When I look at the pkgdown 2.0.2 DESCRIPTION file, it says it depends on R (>= 3.1.0). My limited understanding: pkgdown 2.0.2 should work with R 3.6.3. But ... there may be other dependencies I am unaware of and the entire output from pkgdown would need to be re-reviewed. I look forward to your comments on this.

**Comment by bms63** [comment] 2022-05-05 16:46
Hi Eric.  I installed downlit and using pkgdown 2.0.3 I see the link is no longer rendered @PoojaKumari05.  We should include this package in our list for the updated search function and link this in the PR to close this out.  

![image](https://user-images.githubusercontent.com/10111024/166972418-6fd90ea7-b657-46ba-b979-44cfa6680627.png)

**Closed** 2022-05-23 17:36 UTC
Labels: bug, documentation, release 20-May-2022
