### ISSUE TITLE
GSK to check admiral metadata functionality (2h)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#239] opened 2021-06-17 12:21 UTC
goal: GSK to check which of the listed metadata functionality would be useful for GSK to align with Roche

Identify:
--> issues for company specific functionality 
--> issues for admiral core specific functionality 

Potential functionality:

- Automatically select all predecessor variables from source dataset(s)
- read in parameters

Final Step
- Drop all variables in dataset which are not listed in spec (or output a WARNING?)
- Highlight varaibles in spec but not in dataset?
- Check actual variable type against type specified in spec
- Apply labels from spec to dataset (would this include SDTM vars?)
- Apply formats from spec to dataset (date/datetime formats only)
- Cross-check values of variables against controlled terminology in spec
- Apply length to variables when exporting (already covered in {xport}?)
- Automatically sort by keys provided in spec
- Derive a decode or code variable based on controlled terminology (e.g. you have SEX=M or F and then based on CT you can derived SEXN as 1 or 2 from a CT list)
- Sort variables within datasets as defined in the spec (column order)

**Comment by bundfussr** [comment] 2021-09-22 13:24
Is this a duplicate of https://github.com/Roche-GSK/admiral/issues/383?

**Comment by bundfussr** [comment] 2021-09-23 13:26
What about the question of the scope (already raised in https://github.com/Roche-GSK/admiral/issues/383)?

Shouldn't we answer this question first before we create issues and start implementing functions?

I think especially the derivation functionality requires a concept. 

- Is a structure like metacore where the derivations are described as plain text appropriate? It could end in a bunch of conventions and parsing functions to determine the derivation from the plain text.
- How do we avoid a black box effect? If derivations are read from the metadata and executed automatically, it is hard to see what was done. I think the function which executes a derivation based on metadata should provide additional information what was done.

**Comment by koegerr** [comment] 2021-09-30 06:57
@aehmann-gsk and @lucyhoch 
I added some context to the user stories, this is how Thomas came up with the functions here: https://exbpbox.box.com/s/uks6c8zgiy692dvgoewegvxfelwz9pd9

However, I overall agree with Stefan to fully align between GSK and Roche what we want in terms of functionality. The functions and user stories are a starting point and some might be very company specific.

So to the goal should be to decide:
- do we need Atorus metacore - is there any benefit to it for basic functionality around using parameters, labels, length, formats, high, low values ...
- My suggestion is when there is more clarity around the metadata functionality from GSK we have a breakout group that discusses what we would try/focus on around this and where we are aligned.

@Roche we already had several workshops with our Standards/Metadata team/admiral members/business members that we would not use plain text for derivations in the foreseeable future. So the second bullet @bundfussr mentions is something that we would not see in scope. 
In my opinion it would break the simplicity of admiral and potentially creates a lot of dependencies between systems and documents that would be difficult to manage across companies, even within a company.

**Closed as completed** 2021-10-13 13:32 UTC
Labels: discussion
