### ISSUE TITLE
Our pkgdown site issues

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiral#2103] opened 2023-09-14 17:19 UTC
There are a few things with our pkgdown site that are not functioning at 100%
1. Auto-linking to our pkgdown site is not working and links from other pkgdown websites are directed to the `https://rdrr.io/` site.
2. The pkgdown site's search bar currently re-directs visitors to a different section of our site. For example, if I am on `cran-release` and search `"exprs"` I am linked to a help file from the `0.12.0` section of the website

I _think_ the first point is due to the URL in our DESCRIPTION file points to an HTML re-direct rather than to the location where our site is hosted.

I am more unclear about the second point. Perhaps pkgdown is creating an index for search, and the `cran-release` portion of the index is being over-written by the `v0.12.0` version each time the index is created?

Rather than a change to solve a single issue above, we should solve both simultaneously.

**Comment by bundfussr** [comment] 2023-09-15 09:16
For the first point we also need to consider the documentation of the old versions. For example, in the admiralonco 0.2.0 documentation links to admiral functions should refer to the admiral 0.9.1 documentation.

**Comment by zdz2101** [comment] 2023-09-15 17:03
In the spirit of aligning closer with the R/Datascience community, I think we should actually reconsider hosting only the _latest_ versions of each package on their respective websites. This is what packages like `dplyr` and `tidyr` do, and surely users would be using at least those two packages in their programming workflows too.

I am empathetic to the notion that users should have access to documentation of older versions for maintenance of locked programs locked to specific package versions. But you would have the same problems knowing what was introduced/deprecated in past versions of packages like `dplyr` and `tidyr` too. For example, let's say there were two studies with respective use of `tidyr` before and after `v.1.0.0`. One trial would have access to `pivot_wider()/pivot_longer()` while the other is stuck with `gather()/spread()`. These are the nuances programmers are going to have to face regardless anyway, instead of copy and pasting old code.

With that said, I actually do really like that we provide the website/host documentation of the older versions, but for the issues they **currently** bring up like auto-linking and near-unusable search functionality, I propose that:

We simply _**move**_ the old version hosting to a _separate repo_, perhaps named `admiralarchive` which can simply be a fork of admiral or @ddsjoberg mentioned we can even host all the admiral-family using some black-magic wizardry like he does with `ggsurvfit`. '

This would remedy many of our current problems and instead of a `Versions` button with a long, and ever-expanding, menu dropdown denoted here:
![image](https://github.com/pharmaverse/admiral/assets/43018762/3ea94416-0511-455d-b15e-64c612230cde)

It would just be a reroute to the archive website host with all the past-versions and if/when we have more resources to clean up and maintain older functionality we can address any problems that arise there then.

**Comment by bms63** [comment] 2023-09-15 21:00
I agree with @zdz2101.  The versions is a really cool thing that the CI team put together, but it is adding a lot of complications to our websites.  I worry when we hit maintenance mode this will be a constant issue for us.

Moving all the versions and process to a separate repo outside of the core admiral site could really simplify everything for us.  We could put a link in the readme and in other choice places alerting users to this supported feature.  

I'd also like to see a bunch of the versions removed as they differ so much from `0.12` and I don't think anyone is looking for `0.8.4`...but they could always get it from CRAN archive if they needed it.  `0.12` is much close to a `1.0` or `2.0` then say `0.7.1`...i hope.

**Comment by bundfussr** [comment] 2023-09-18 08:50
Why should it be easier if we move the older versions to admiralarchive? admiralarchive would contain all versions except the latest. So I would expect the same issues there. (And we would have another repo to maintain.)

Maybe we should implement a function where the URL of the package and the URLs of the admiral dependencies can be specified. For example
```
build_admiral_site(
  url = "https://pharmaverse.github.io/admiralonco/v0.4.0/",
  urls_dep = list(
    admiral = "https://pharmaverse.github.io/admiral/v0.11.1/",
    admiraldev = "https://pharmaverse.github.io/admiraldev/v0.4.0/"
  )
)
```
The function would call `pkgdown::build_site()` and then update the links according to the specified URLs.

**Comment by bms63** [comment] 2023-09-18 12:33
> Why should it be easier if we move the older versions to admiralarchive? admiralarchive would contain all versions except the latest. So I would expect the same issues there. (And we would have another repo to maintain.)
> 
> Maybe we should implement a function where the URL of the package and the URLs of the admiral dependencies can be specified. For example
> 
> ```
> build_admiral_site(
>   url = "https://pharmaverse.github.io/admiralonco/v0.4.0/",
>   urls_dep = list(
>     admiral = "https://pharmaverse.github.io/admiral/v0.11.1/",
>     admiraldev = "https://pharmaverse.github.io/admiraldev/v0.4.0/"
>   )
> )
> ```
> 
> The function would call `pkgdown::build_site()` and then update the links according to the specified URLs.

The Search and cross-linking abilities are not working well.  The root of the issue seems to be how we have implemented the Versions-process on our websites.  Removing the Versions-processes allows us to regain all the basic functionality given to us by pkgdown.   This seems to be the simplest solution right now.

I **_100% love the Version part of the website_**, but if it is reducing the users' abilities to Search and use cross-linking then I think we should abandon it for something simpler.   Personally, I don't think this is a simple problem to solve or the CI team would have put something out for us.  Spending time on this while we work on the function re-work could be time-consuming and honestly frustrating as I don't think any of us have a lot of web-based wizardry (unless @bundfussr you have more secret skills :) ) 

I think if we went the way of the archive repo, then we would not have the linking between packages.  However, I'm guessing someone could bake the cross-linking into the archive-repo if that was desired.  The advantage of doing this in another repo is the first port of contact for admiral works 100% with regards to Search and Cross-Linking.   We can experiment, break things, implement temporary solutions in the archive-repo, but know that there is zero impact to the main admiral website.

We can always come back to this process later and re-implement.  Perhaps a series of dummy repos could be set up to try and figure out this process.

**Comment by dgrassellyb** [comment] 2023-09-18 16:42
Tagging @cicdguy here to let him aware of this issue ! 

@ddsjoberg : 
1. for the auto linking we can try to replace url in the description with `https://pharmaverse.github.io/admiral/cran-release/` to avoid redirection and see if the issue is coming from this.. ? but I am not sure, I spent some time reading pkgdown documentation and I am a bit curious to find out why these references from external packages are not working ..

For 2. : 
I think it's not really an issue, it's more related on how we build cran-release ref : 
https://github.com/insightsengineering/r-pkgdown-multiversion/blob/main/action.yml (if you look the use of parameter `latest-tag-alt-name` which is set-up to `cran-release` for admiral, it's just doing a copy of latest version (so that's why cran-release then gives references to `0.12.0` I think) - I just made a quick example, for exemple taking `0.10.0` I don't see problems with the global search 
![pkgdown](https://github.com/pharmaverse/admiral/assets/56442075/d684908a-bcdc-4968-bf76-3607c4366bbe)


but I understand that you'd like to move old versions in another repo (especially because you told me in our call today that having too much versions references in the search bar is not suitable)
Then we would move old versions to an `admiralarchive` repo - but then we would need to update ci-workflows to be able to do the following steps for each new release : 
- building the doc for old releases and pushing this changes to admiralarchive repo (and then this would trigger another pkgdown build job) 
- building latest version only for admiral doc
Not sure about this solution I guess it would need further discussions especially with Dinakar..

**Comment by dgrassellyb** [comment] 2023-09-19 07:03
> wow, thank you @dgrassellyb !
> 
> I don't think we necessarily need to host the old versions of the website in a separate repo. Was just thinking of some ways that may solve searching, but if you've already solved it likely no need to do that?

Mmh I will maybe test again the searching search bar to be sure everything works properly :) 
also good new, I've seen that Adam has been working on this PR : https://github.com/pharmaverse/admiralci/pull/141/files - @galachad looking at this action you did it seems that it's fixing these broken links to rdrr ? (and since it's done in admiralci pkgdown workflow it will fix also borken links on other admiral packages)

**Comment by galachad** [comment] 2023-09-19 09:13
I can imagine that the docs is linking to the packages that are not installed in the environment, but in this case I think it was caused by multi versions. This PR fix links if direct url is not available, all other links should work as expected, as the URL is taken from the DESCRIPTION file. 
 
@dgrassellyb this PR is ready and waiting for review.

**Comment by bms63** [comment] 2023-09-19 14:56
So if this all works then great and my proposal can be dropped.

but...

We only have so many people who are skilled in this area. (@galachad @dgrassellyb and @cicdguy ) and my understanding is that @galachad and @cicdguy are not on this project anymore (maybe still in spirit!!) and @dgrassellyb has to really focus their time on admiral.

The versioning piece is so cool, but again makes admiral "more unique" in the world of R packages.  This uniqueness I see adds a lot more complication.  The simplification proposal (archive-repo) is way to reduce the burden of long-term upkeep of the website.  I'm nervous as this is an advanced and complicated component of admiral and as @dgrassellyb moves on to other projects that a **_core admiral developer will not have the skills_** to fix the website issues that come up as updates come into pkgdown, github actions and the releases of admiral grow (although hopefully at a reduce pace).


If everything is successful (links work and search is solid) is there a way to develop any tests that can help us monitor these issues when a new release is done?  This automated testing sounds complicated too!  But maybe can give us more confidence that everything is working when releases are completed.

**Comment by bundfussr** [comment] 2023-09-19 15:18
I think the important point is that everything is well documented. For example, regarding documentation workflow we have
![image](https://github.com/pharmaverse/admiral/assets/80953585/7ad21487-3495-49b1-af77-c4f76d6d078e)
It is not clear for which versions the workflow creates the documentation and how to add versions which are not created by the workflow.

**Comment by dgrassellyb** [comment] 2023-09-20 15:11
> I think the important point is that everything is well documented. For example, regarding documentation workflow we have ![image](https://user-images.githubusercontent.com/80953585/269006944-7ad21487-3495-49b1-af77-c4f76d6d078e.png) It is not clear for which versions the workflow creates the documentation and how to add versions which are not created by the workflow.

@bundfussr : you can find a detailed documentation here : https://github.com/insightsengineering/r-pkgdown-multiversion - you can see that the argument `branches-or-tags-to-list` refers to the versions dropdown - Admiralci is mostly using some more generic actions (that can be used for any other R package) that's why not every documentation can be find directly inside admiralci repo (What we can do is quickly add a link to the external github actions documenation)

**Comment by dgrassellyb** [comment] 2023-09-20 16:30
> So if this all works then great and my proposal can be dropped.
> 
> but...
> 
> We only have so many people who are skilled in this area. (@galachad @dgrassellyb and @cicdguy ) and my understanding is that @galachad and @cicdguy are not on this project anymore (maybe still in spirit!!) and @dgrassellyb has to really focus their time on admiral.
> 
> The versioning piece is so cool, but again makes admiral "more unique" in the world of R packages. This uniqueness I see adds a lot more complication. The simplification proposal (archive-repo) is way to reduce the burden of long-term upkeep of the website. I'm nervous as this is an advanced and complicated component of admiral and as @dgrassellyb moves on to other projects that a **_core admiral developer will not have the skills_** to fix the website issues that come up as updates come into pkgdown, github actions and the releases of admiral grow (although hopefully at a reduce pace).
> 
> If everything is successful (links work and search is solid) is there a way to develop any tests that can help us monitor these issues when a new release is done? This automated testing sounds complicated too! But maybe can give us more confidence that everything is working when releases are completed.

For now we can still work on existing broken links for older versions (and fix this issue for new versions with what Adam did, I just need to review the PR) 
About this archive repo for the documentation I just want to wait for @cicdguy thoughts before going deeper into this (He's back the 2nd of october) 
About automated testing : It could works to detect non existing links, 404 errors.. but I am not sure there is a way to detect that the search is solid it seems super tricky to do ..)

**Comment by bundfussr** [comment] 2023-09-21 11:32
> > I think the important point is that everything is well documented. For example, regarding documentation workflow we have ![image](https://user-images.githubusercontent.com/80953585/269006944-7ad21487-3495-49b1-af77-c4f76d6d078e.png) It is not clear for which versions the workflow creates the documentation and how to add versions which are not created by the workflow.
> 
> @bundfussr : you can find a detailed documentation here : https://github.com/insightsengineering/r-pkgdown-multiversion - you can see that the argument `branches-or-tags-to-list` refers to the versions dropdown - Admiralci is mostly using some more generic actions (that can be used for any other R package) that's why not every documentation can be find directly inside admiralci repo (What we can do is quickly add a link to the external github actions documenation)

Yes, if an external action is used, a link to its documentation should be provided. What still is not clear to me if the documentation action just updates the "Versions" menu or if it also updates the folders in `gh-pages`.

**Comment by bundfussr** [comment] 2023-09-21 11:37
> About automated testing : It could works to detect non existing links, 404 errors.. but I am not sure there is a way to detect that the search is solid it seems super tricky to do ..)

I would guess that we could checl the URLs of the form `"path":"https://pharmaverse.github.io/admiral/CODE_OF_CONDUCT.html"` in `search.json`. However, the file is quite large, i.e., the check could be very time-consuming.

**Comment by bms63** [comment] 2023-09-22 18:10
Hi all,

This appears to have been fixed by @dgrassellyb and @galachad.  We will have a new deployment on Monday/Tuesday so can verify if everything is solid.

I made two issues in `admiralci` from this discussion:
- https://github.com/pharmaverse/admiralci/issues/150
- https://github.com/pharmaverse/admiralci/issues/149

**Closed by bms63** 2023-09-22 18:10 UTC
