### ISSUE TITLE
create a programming workflow for QS (6h)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#374] opened 2021-07-19 12:44 UTC
goal: identify common BDS functionality and special QS functionality. Create QS specific functional issues.

**Comment by bms63** [comment] 2022-04-25 20:23
@pharmaverse/admiral HI everyone.  

I would like to start thinking about making the workflow for this ADQS in our next cycle after the upcoming CRAN release (May 13th) and if needed develop functions and a template script.  

Like ADLB, I have never had the opportunity to build an ADQS dataset, but I look forward to this opportunity.  If we go forward with this - are their others interested?  I missed the first wave of admiral development, so being able to build functions and a dataset script were really fun for me for ADLB!!    We could write some new functions, enhance others and make a new ADQS template script!  It will be an adventure that I am sure of!

Does anyone habe resources for ADQS- a quick google search turns up these two - I didn't dig into CDISC website yet.
*  [Implementing Patient Report Outcome Data in Clinical Trials Analysis](https://www.pharmasug.org/proceedings/2017/PO/PharmaSUG-2017-PO04.pdf?msclkid=489e3e54c4d411ecadece01a6ef2e8c1)
*  [ADQRS: Basic Principles for Building Questionnaire, Rating and Scale Analysis 
Datasets](https://www.lexjansen.com/pharmasug/2017/DS/PharmaSUG-2017-DS24.pdf?msclkid=489e7438c4d411ec941c080b5c7977b0)

Please post here if you have ideas, resources, etc.  Posting doesn't mean you have to participate in the ADQS development.

**Comment by bundfussr** [comment] 2022-04-26 10:03
@bms63 , I am interested in contributing to this issue. I am not sure if it possible to create a workflow or template script because there are so many questionnaires and so many endpoints. In the Roche standard no ADQS dataset covering all questionnaires is defined but separate datasets for each questionnaire, e.g., ADCSSRS and ADQLQC. Thus the development process and the result may be different compared to the other datasets we have considered so far.

**Comment by thomas-neitmann** [comment] 2022-04-28 09:15
I certanly do not know much about questionnaire type datasets but I certainly know that there are a lot of different questionnaire out there with different ratings and scales and each questionnaire would most likely need specific functions. Would it make sense to start tackling a couple of commonly used questionnaire (e.g. EORTC, SF-36 QOL) in an admiral extension package?

**Comment by bms63** [comment] 2022-04-28 13:05
I've seen a lot of sf-36 on the the studies I've worked on, but never developed the datasets just the associated displays.  

Be cool to see an `admiralqs` package. 

I would think we should first develop some functions and a template within admiral and then if the number of associated functions grows too big, then move it out into its own specific package.

**Comment by bundfussr** [comment] 2022-04-28 14:24
@rossfarrugia , should we share the Roche Analysis Dataset Standard Specification 2? It provides a lot more questionnaires ADaMs specifications.

**Comment by millerg23** [comment] 2022-04-28 15:32
@bms63 happy to get involved in this if required. I worked on implementing questionnaires in Roche with Stefan, agree with sentiments of focussing on particular questionnaires and build up the set of tools required.

**Comment by bms63** [comment] 2022-04-29 14:54
Thanks Stefan!  @lucyhoch and @upadhyor do know which specs we can share that are related to our questionnaire ADaMs?

**Comment by koegerr** [comment] 2022-05-11 13:19
Hi,

I am currently working with the Neuroscience POD ADS Leads to collect all neuro endpoints (mainly questionnaires). The goal is to see how we can harmonize the approaches as much as possible. Not just the programming but also what metadata to generate and what documents to store and how to document the analysis.

@bundfussr and @millerg23 I will reach out to you when we have all the content together.
Overall I agree, that we potentially need multiple solutions here. Depending on the type of questionnaire.

@bms63 I will reach out for some brainstorming when ready.

I suggest to keep this in the backlog for now.

**Comment by bundfussr** [comment] 2022-06-27 11:24
I had a rough look at the Roche questionnaires specs. There are two main types of questionnaires ADaM datasets:

- Analysis datasets for descriptive statistics
- Time to event analysis datasets

It seems that most of the algorithms for deriving questionnaires parameters are very similar. Common types are:
- *Original items*: SDTM variables are mapped to `AVAL`, `AVALC`, `PARAMCD`. Variables like `CHG`, `CHGCAT1`, ... are derived.
- *Scales*: The average of certain original items is calculated and normalized, e.g., to the range from 0 to 100. Usually this is derived only if at least 50% of the original items were answered.
- *Worst answer*: From certain original items the worst answered with yes is selected.
- *Completion*: Parameter indicating if at least n questions or p% of all questions were answered.
- *Time to deterioration*: results worsened compared to baseline by a certain amount
- *Time to confirmed deterioration*: results worsened compared to baseline by a certain amount for at least two consecutive assessments.
- *Time to definitive deterioration*: results worsened compared to baseline by a certain amount for all following assessments.

General functions for these common types could be implemented in admiral core. These function could read in metadata which defines for example which original items are to be used for a certain scale.

CDISC defines standard SDTM values for certain questionnaires (see https://www.cdisc.org/standards/foundational/qrs). I.e., some of the metadata can be defined at admiral core level (if copyrights allows). However, the final metadata used for a derivation needs to be collected from different levels. For example to derive the suicidal behavior endpoint the original items to be used could be defined by admiral core while the `PARAMCD` values are defined in a company specific admiral extension package. 

Of course, it would be helpful to take specs from other companies into account. I hope we can solve the box issue such that the GSK specs can be shared.

**Comment by bms63** [comment] 2022-06-27 12:31
I uploaded the adcssrs spec for GSK.  https://exbpbox.box.com/s/8dzxsts0zjdgp9kz6ylz2gltey9vgpwt

**Comment by esimms999-gsk** [comment] 2022-06-27 12:43
As @bms63 has shown, GSK still has access to Box. I lost access either because I got a replacement laptop or the maximum length of the GSK exemption to have access to Box (90 days) ran out.

**Comment by bms63** [comment] 2022-06-27 21:07
> I had a rough look at the Roche questionnaires specs. There are two main types of questionnaires ADaM datasets:
> 
> * Analysis datasets for descriptive statistics
> * Time to event analysis datasets
> 
> It seems that most of the algorithms for deriving questionnaires parameters are very similar. Common types are:
> 
> * _Original items_: SDTM variables are mapped to `AVAL`, `AVALC`, `PARAMCD`. Variables like `CHG`, `CHGCAT1`, ... are derived.
> * _Scales_: The average of certain original items is calculated and normalized, e.g., to the range from 0 to 100. Usually this is derived only if at least 50% of the original items were answered.
> * _Worst answer_: From certain original items the worst answered with yes is selected.
> * _Completion_: Parameter indicating if at least n questions or p% of all questions were answered.
> * _Time to deterioration_: results worsened compared to baseline by a certain amount
> * _Time to confirmed deterioration_: results worsened compared to baseline by a certain amount for at least two consecutive assessments.
> * _Time to definitive deterioration_: results worsened compared to baseline by a certain amount for all following assessments.
> 
> General functions for these common types could be implemented in admiral core. These function could read in metadata which defines for example which original items are to be used for a certain scale.
> 
> CDISC defines standard SDTM values for certain questionnaires (see https://www.cdisc.org/standards/foundational/qrs). I.e., some of the metadata can be defined at admiral core level (if copyrights allows). However, the final metadata used for a derivation needs to be collected from different levels. For example to derive the suicidal behavior endpoint the original items to be used could be defined by admiral core while the `PARAMCD` values are defined in a company specific admiral extension package.
> 
> Of course, it would be helpful to take specs from other companies into account. I hope we can solve the box issue such that the GSK specs can be shared.

So this is a really good summary.  Would it be helpful to develop some pseudo code for each common type and then put out onto admiral slack?  See if we can collect any feedback before we start coding these up?

**Comment by bundfussr** [comment] 2022-07-01 14:20
I have created issues for the proposals for the ADQS parameter types: https://github.com/pharmaverse/admiral/issues/1277, https://github.com/pharmaverse/admiral/issues/1278, https://github.com/pharmaverse/admiral/issues/1279, https://github.com/pharmaverse/admiral/issues/1280, https://github.com/pharmaverse/admiral/issues/1281, https://github.com/pharmaverse/admiral/issues/1282, https://github.com/pharmaverse/admiral/issues/1283.

**Comment by esimms999-gsk** [comment] 2022-07-01 14:39
Additional feedback from GSK group responsible for ADaM specs:

- There is an oncology PRO working group which is also questionnaire-based data. I believe their work should also be taken into consideration when developing a standard ADQS specs.
- We should try to have one PRO dataset (if possible), at least that’s what we will aim for in Oncology. However, this may not be possible given different TAs have different types of questionnaires.

**Comment by bundfussr** [comment] 2022-07-01 14:46
@esimms999-gsk , does the GSK PRO working group define standard datasets or parameters? In the affirmative, could you share the specs?

As admiral has a modular approach, it does not matter if you create a single PRO dataset or seperate PRO datasets for each questionnaire. Once we have the functions for the parameters, it should be easy to create both.

**Comment by koegerr** [comment] 2022-07-06 12:23
Thanks a lot for your proposal Stefan. I didn't had time to look at them in detail yet but I spoke with various people around the general questionnaire topic and there is a strong feeling that this needs a bit more discussion. Some points raised so far:

- The provisional specs should not necessarily be used yet to create any functions. 
- Metadata should not be stored and maintained by admiral, it should be governed internally also due to the copyrights
- At Roche we usually have one dataset per questionnaire, this should be considered

I still have an outstanding meeting with our PCOR group head around copyrights and additional input.

I also showed the created issue to one of the ADaM experts and she was not sure where these come from. WOuld be great if we can discuss them in more detail.

**Comment by bms63** [comment] 2023-01-30 15:06
Closing as WF has been created and issues create for "certain" functions

**Closed by bms63** 2023-01-30 15:06 UTC
Labels: BDS, Questionnaires, ADQS, release Q1-2023
